language: python
dist: xenial
python:
    - "3.7"

install:
    - pip install tox-travis tox pre-commit

script:
    - travis_wait 45 tox
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pre-commit run --show-diff-on-failure --origin $TRAVIS_COMMIT --source $TRAVIS_BRANCH; fi'

notifications:
    email:
        recipients:
            - psangkloy@argo.ai
        on_success: change
        on_failure: change
