SensorDatasetConfig:
  _target_: argoverse.sensor_dataset_config.SensorDatasetConfig
  dataset_name: argoverse1.1
  ring_cam_fps: 30
  stereo_cam_fps: 5

  # all ring cameras are `landscape` aspect ratio
  sensors:
    _target_: argoverse.sensor_dataset_config.SensorDimensions
    
    ring_front_center: 
      _target_: argoverse.sensor_dataset_config.ImageDimensions
      height: 1200
      width: 1920

    ring_front_left:
      _target_: argoverse.sensor_dataset_config.ImageDimensions
      height: 1200
      width: 1920

    ring_front_right:
      _target_: argoverse.sensor_dataset_config.ImageDimensions
      height: 1200
      width: 1920

    ring_side_left:
      _target_: argoverse.sensor_dataset_config.ImageDimensions
      height: 1200
      width: 1920

    ring_side_right:
      _target_: argoverse.sensor_dataset_config.ImageDimensions
      height: 1200
      width: 1920

    ring_rear_left:
      _target_: argoverse.sensor_dataset_config.ImageDimensions
      height: 1200
      width: 1920

    ring_rear_right:
      _target_: argoverse.sensor_dataset_config.ImageDimensions
      height: 1200
      width: 1920

    stereo_front_right:
      _target_: argoverse.sensor_dataset_config.ImageDimensions
      height: 2056
      width: 2464

    stereo_front_left:
      _target_: argoverse.sensor_dataset_config.ImageDimensions
      height: 2056
      width: 2464
